# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTkyNTI2OTIzMjViODlhMmY5ZWZlZDc5NWI3OWI5MzQwNTllODJlMzBlZGEwMjUxYjY1NDJlNjMyN2VhMzYyM2NlNWIyNzk1MGQxYWY1ODkwMWUyMGFhZDc3Njk5OGVlNGVjZWIzNjQ4YTAxNTUwZDlmMzA1ZDIwY2QxZWVlMDI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
